<?php
/**
 * Created by PhpStorm.
 * User: 平行软件科技有限公司
 * Date: 2017/12/12 0012
 * Time: 上午 10:03
 */

use think\Route;

//安装路由
Route::post("InstallDataBase","install/index/step3");
//下载检测
Route::get("Detection/download","Admin/Detection/download");
Route::get("Detection/install","Admin/Detection/install");
Route::get("ObtainIp","Admin/Detection/getIp");
//重新配置文件
Route::post("fileByConfigure","Admin/Upload/fileByConfigure");
//登录页面
Route::get("login","Login/Login/login");
Route::post("getLogin","Login/Login/getLogin");
//注册页面
Route::get("register","Login/Register/register");
Route::post("getRegister","Login/Register/getRegister");
//用户管理
Route::get("User","Admin/User/user");
Route::post("User/disableByEnable","Admin/User/disableByEnable");
Route::get("UserEdit","Admin/User/edit");
Route::post("UserEdit","Admin/User/edit");
Route::post("getEnable","Admin/User/getEnable");
//添加用户
Route::get("User/add","Admin/User/add");
Route::post("User/add","Admin/User/add");
//用户修改密码
Route::get("User/Password","Admin/User/Password");
Route::post("User/Password","Admin/User/Password");
//修改用户信息
Route::get("User/EditInfo","Admin/User/EditInfo");
Route::post("User/EditInfo","Admin/User/EditInfo");
//退出登录
Route::post("Logout","Admin/User/Logout");
//配置管理
Route::get("Config","Admin/Config/index");
Route::post("Config","Admin/Config/index");
//图片管理
Route::get("Upload","Admin/Upload/index");
Route::post("Upload/delete","Admin/Upload/delete");
Route::get("Upload/getUpload","Admin/Upload/getUpload");
Route::post("Upload/getDel","Admin/Upload/getDel");
Route::post("Upload/pictureEnlarge","Admin/Upload/picture");
//图片批量删除
Route::post("Upload/getDelete","Admin/Upload/getDelete");
//清空缓存
Route::post("getCaching","Admin/Upload/getCaching");
//清除令牌缓存
Route::post("getToken","Admin/Upload/getToken");
//文件编辑器上传图片
Route::post("lay_img_upload","Admin/Upload/lay_img_upload");
//文章类型
Route::get("Type","Admin/Article/type");
Route::get("Type/add","Admin/Article/typeAdd");
Route::post("Type/add","Admin/Article/typeAdd");
Route::get("Type/typeEdit","Admin/Article/typeEdit");
Route::post("Type/typeEdit","Admin/Article/typeEdit");
Route::post("Type/typeDelete","Admin/Article/typeDelete");
//文章管理
Route::get("Article/Add","Admin/Article/add");
Route::post("Article/Add","Admin/Article/add");
Route::get("Article","Admin/Article/index");
Route::get("Article/edit","Admin/Article/edit");
Route::post("Article/edit","Admin/Article/edit");
Route::post("Article/Delete","Admin/Article/delete");
//是否置顶
Route::post("Article/Recycle","Admin/Article/Recycle");
//加入回收站
Route::post("RecycleOne","Admin/Article/RecycleOne");
//回收站
Route::get("Article/Recovery","Admin/Article/recovery");
//文章评论
Route::get("Comment","Admin/Comment/index");
Route::get("Comment/Add","Admin/Comment/add");
Route::post("Comment/Add","Admin/Comment/add");
Route::get("Comment/edit","Admin/Comment/edit");
Route::post("Comment/edit","Admin/Comment/edit");
Route::post("Comment/delete","Admin/Comment/delete");

//导航管理
Route::post("Navigation/group","Admin/Navigation/group");
Route::get("Navigation/Add","Admin/Navigation/add");
Route::post("Navigation/Add","Admin/Navigation/add");
Route::get("Navigation/edit","Admin/Navigation/edit");
Route::post("Navigation/edit","Admin/Navigation/edit");
//主部导航
Route::get("Navigation/main","Admin/Navigation/main");
//底部导航
Route::get("Navigation/bottom","Admin/Navigation/bottom");
//禁用或启用
Route::post("Navigation/DisableAndEnabled","Admin/Navigation/DisableAndEnabled");
//批量禁用和启用
Route::post("Navigation/getDisableAndEnabled","Admin/Navigation/getDisableAndEnabled");
//删除
Route::post("Navigation/Delete","Admin/Navigation/delete");
//公告管理
Route::get("Notice","Admin/Notice/index");
Route::get("Notice/Add","Admin/Notice/add");
Route::post("Notice/Add","Admin/Notice/add");
Route::get("Notice/edit","Admin/Notice/edit");
Route::post("Notice/edit","Admin/Notice/edit");
Route::post("Notice/Delete","Admin/Notice/Delete");
//公告禁用或启用
Route::post("Notice/DisableAndEnabled","Admin/Notice/DisableAndEnabled");
//公告批量禁用或启用
Route::post("Notice/getDisableAndEnabled","Admin/Notice/getDisableAndEnabled");



//前台
Route::get("download","index/index/download");
Route::post("downloadUpload","index/index/downloadUpload");